import type { Citation, Deliverable } from './types';
import type { useStore } from './store';
import { personById } from '@/data/people';
import { PHASES, appHref, fmtK, wsLabel } from './meta';
import { fmtDate } from './atlas';

// Controlled generation: deliverables are assembled from structured deal data
// (findings, risks, decisions, valuation), not free-written by a model. In the
// product a model would polish prose inside each section, not invent content.

type S = ReturnType<typeof useStore.getState>;
type Inline = string | { type: 'text'; text: string; styles: Record<string, boolean> } | { type: 'link'; href: string; content: string };
type Block = { type: string; props?: Record<string, unknown>; content?: Inline[] | string | unknown; children?: Block[] };

const h = (level: 1 | 2 | 3, text: string): Block => ({ type: 'heading', props: { level }, content: text });
const p = (...c: Inline[]): Block => ({ type: 'paragraph', content: c });
const b = (text: string): Inline => ({ type: 'text', text, styles: { bold: true } });
// Secondary notes in generated documents: same type family, no italics.
const i = (text: string): Inline => ({ type: 'text', text, styles: {} });
const li = (...c: Inline[]): Block => ({ type: 'bulletListItem', content: c });
const ni = (...c: Inline[]): Block => ({ type: 'numberedListItem', content: c });
const table = (rows: string[][]): Block => ({ type: 'table', content: { type: 'tableContent', rows: rows.map((cells) => ({ cells })) } });

const name = (id: string) => (id === 'atlas' ? 'Atlas' : personById(id)?.name ?? id);

function cite(s: S, acqId: string, c: Citation[]): Inline[] {
  if (!c.length) return [];
  const out: Inline[] = [' ['];
  c.forEach((x, idx) => {
    const d = s.documents.find((d) => d.id === x.docId);
    if (!d) return;
    const short = d.name.replace(/\.(pdf|xlsx|docx|pptx|csv)$/i, '').split(' — ')[0];
    out.push({ type: 'link', href: appHref(`/acquisitions/${acqId}/documents/${d.id}${x.page ? `?page=${x.page}` : ''}`), content: `${short}${x.page ? `, p.${x.page}` : ''}` });
    if (idx < c.length - 1) out.push('; ');
  });
  out.push(']');
  return out;
}

export function generate(type: Deliverable['type'], acqId: string, s: S): Block[] {
  const acq = s.acquisitions.find((a) => a.id === acqId)!;
  const findings = s.findings.filter((f) => f.acqId === acqId && !['Dismissed', 'Proposed'].includes(f.status));
  const risks = s.risks.filter((r) => r.acqId === acqId && r.status !== 'Closed');
  const decisions = s.decisions.filter((d) => d.acqId === acqId);
  const open = decisions.filter((d) => d.status === 'Open' || d.status === 'Under Review');
  const sev = { Critical: 0, High: 1, Medium: 2, Low: 3 };
  const keyFindings = findings.filter((f) => !f.positive).sort((a, b) => sev[a.severity] - sev[b.severity]);
  const positives = findings.filter((f) => f.positive);
  const t = acq.target;

  const disclaimer = p(i(`SYNTHETIC DEMO DATA · Generated by Atlas from structured deal data on ${fmtDate(new Date().toISOString().slice(0, 10))}. Facts carry source references; interpretations are labeled. Review before circulating.`));

  if (type === 'IC Memo') {
    const price = decisions.find((d) => d.id === 'dec-price');
    return [
      disclaimer,
      h(1, `Investment Committee Memorandum — ${acq.name}`),
      p(b('Project: '), acq.codename, b('   Prepared by: '), name(acq.dealLeadId), b('   Target close: '), acq.targetClose ? fmtDate(acq.targetClose) : 'TBD'),
      h(2, '1. Transaction overview'),
      p(`Acquisition of 100% of ${t.legalName} (${t.industry}), headquartered in ${t.hq}. Working enterprise value $${acq.ev.toFixed(1)}M — ${acq.evBasis.replace(/\.$/, '')}.`),
      h(2, '2. Strategic rationale'),
      p(acq.thesis.summary),
      ...acq.thesis.pillars.map((x) => li(x)),
      h(2, '3. Target profile'),
      table([
        ['Metric', 'Value'],
        ['Revenue (FY2025)', `$${t.revenue.toFixed(1)}M`],
        ['Adjusted EBITDA', `$${t.ebitda.toFixed(2)}M (${t.ebitdaBasis})`],
        ['Employees', String(t.employees)],
        ['Branches', t.branches.join(', ')],
        ['Ownership', t.ownership],
      ]),
      h(2, '4. Valuation'),
      ...(acq.valuation
        ? [
            p(acq.valuation.note),
            table([['EBITDA bridge', 'FY2025'], ...acq.valuation.lines.map((l) => [l.label, l.kind === 'adjustment' ? `(${fmtK(-l.value)})` : fmtK(l.value)])]),
            p(...cite(s, acqId, [{ docId: 'd-qoe', page: 11 }, { docId: 'd-fin', page: 3 }])),
          ]
        : [p('Valuation not yet built.')]),
      ...(price
        ? [p(b('Price decision: '), price.status === 'Approved' ? `Approved — ${price.options.find((o) => o.id === price.outcome?.optionId)?.label}.` : `Pending — recommended: ${price.options.find((o) => o.id === price.recommendation?.optionId)?.label}.`)]
        : []),
      h(2, '5. Key findings'),
      ...keyFindings.slice(0, 6).flatMap((f, idx) => [
        h(3, `Finding ${idx + 1} — ${f.title}`),
        p(b('Fact: '), f.fact.text, ...cite(s, acqId, f.fact.citations)),
        ...(f.interpretation ? [p(b('Interpretation: '), f.interpretation)] : []),
      ]),
      ...(positives.length ? [h(3, 'Supporting findings'), ...positives.map((f) => li(f.title, ...cite(s, acqId, f.fact.citations)))] : []),
      h(2, '6. Key risks and mitigations'),
      table([['Risk', 'Severity', 'Mitigation', 'Owner'], ...risks.map((r) => [r.title, r.severity, r.mitigation, name(r.ownerId)])]),
      h(2, '7. Thesis assumptions'),
      table([['Assumption', 'Expected', 'Current', 'Status'], ...acq.thesis.assumptions.map((a) => [a.label, a.expected, a.current ?? '—', a.status])]),
      h(2, '8. Integration considerations'),
      ...findings.flatMap((f) => f.implications.filter((x) => x.area === 'Integration').map((x) => li(x.text))),
      h(2, '9. Recommendation'),
      p(i('To be written by the deal lead. Atlas does not draft the investment recommendation.')),
      h(2, '10. Decisions required from IC'),
      ...(open.length ? open.map((d) => ni(b(d.question), ` — approver ${name(d.approverId)}${d.recommendation ? `; recommended: ${d.options.find((o) => o.id === d.recommendation!.optionId)?.label}` : ''}`)) : [p('None outstanding.')]),
    ];
  }

  if (type === 'Management Meeting Brief') {
    return [
      disclaimer,
      h(1, `Management Meeting Brief — ${acq.name}`),
      p(b('Meeting: '), 'Management meeting #2, Mon Oct 5, Austin HQ. ', b('Attendees: '), 'Gary Castillo, Austin GM; Marcus Hale, Priya Raman, Rachel Kim.'),
      h(2, 'Objectives'),
      li('Close out open diligence questions that affect price and structure.'),
      li('Test founder transition and license succession.'),
      li('Agree approach to top-customer outreach.'),
      h(2, 'Issues to clarify'),
      ...keyFindings.slice(0, 5).map((f) => li(b(f.title + '. '), f.fact.text, ...cite(s, acqId, f.fact.citations))),
      h(2, 'Questions for management'),
      ni('Who would be licensed as the ACR qualifier for Austin and Round Rock, and how long would TDLR take?'),
      ni('Walk us through the Brazos Valley ISD relationship and the 2023 MSA renewal.'),
      ni('Warranty claims recurred in each of the last 3 years. What drives them?'),
      ni('Where are technicians going when they leave? What would you change?'),
      ni('Should we approach Lakeline together before announcement?'),
      ni('What is the plan to complete EPA 608 logs at Waco?'),
      h(2, 'Lessons from prior acquisitions'),
      li(b('Bluebonnet Plumbing (2023): '), 'founder was sole license holder; bidding paused 4 months post-close.'),
      li(b('Red River Mechanical (2025): '), 'largest customer left 9 months after close; no contingent consideration.'),
      h(2, 'Do not discuss'),
      li('Revised price — pending IC on Oct 14.'),
    ];
  }

  if (type === 'Weekly Deal Update') {
    const recent = s.activity.filter((a) => a.acqId === acqId && a.at >= '2026-09-26');
    return [
      disclaimer,
      h(1, `Weekly Deal Update — ${acq.name}`),
      p(b('Status: '), acq.stageLabel, '. ', b('Target close: '), acq.targetClose ? fmtDate(acq.targetClose) : 'TBD'),
      h(2, 'Headline'),
      p('QoE draft reduces adjusted EBITDA by $420K. Revised price proposal ($20.0M + up to $1.5M earn-out) is with the CEO for approval ahead of IC on Oct 14. Exclusivity extended to Dec 15.'),
      h(2, 'Progress by phase'),
      table([['Phase', 'Status', 'Progress'], ...PHASES.map((ph) => [ph.short, acq.phases[ph.key].status, `${acq.phases[ph.key].progress}%`])]),
      h(2, 'What changed this week'),
      ...recent.map((a) => li(`${name(a.actor)} ${a.text}`)),
      h(2, 'Decisions pending'),
      ...open.map((d) => li(d.question, ` — ${name(d.approverId)}${d.due ? `, due ${fmtDate(d.due)}` : ''}`)),
      h(2, 'Next week'),
      li('Management meeting #2 (Oct 5)'),
      li('Complete BVISD and Lakeline customer calls'),
      li('QoE final report'),
    ];
  }

  if (type === 'Day 1 Plan') {
    const integ = findings.flatMap((f) => f.implications.filter((x) => x.area === 'Integration').map((x) => ({ f, x })));
    return [
      disclaimer,
      h(1, `Day 1 Plan — ${acq.name}`),
      p(b('Integration lead: '), 'Rachel Kim. ', b('Day 1: '), 'Mon Nov 23, 2026 (planned).'),
      h(2, 'Day 1 must-haves'),
      li('Customer and employee announcements (sequenced: employees 7am, top-5 customers by noon).'),
      li('License qualifier in place for all three branches.'),
      li('Payroll and benefits continuity confirmed.'),
      li('Banking: lockbox and sweep to Meridian treasury.'),
      li('Insurance: ABC added to Meridian program.'),
      h(2, 'Integration implications from diligence'),
      ...integ.map(({ f, x }) => li(x.text, ' ', i(`(from: ${f.title})`))),
      h(2, 'Key integration decisions'),
      ...decisions.filter((d) => d.phase === 'integration').map((d) => li(d.question, ` — ${d.status}`)),
      h(2, 'Workstreams'),
      table([
        ['Workstream', 'Owner', 'Day 1', 'Day 30', 'Day 100'],
        ['People', 'Tom Brennan', 'Announcements; retention letters', 'Pay-band alignment', 'Benefits migration'],
        ['Customers', 'Marcus Hale', 'Top-5 calls with Gary', 'Relationship owner map', 'Fire/life-safety cross-sell pilot'],
        ['Finance', 'Elena Torres', 'Bank accounts; AP cutover', 'Month-end close on Meridian ERP', 'Sales tax VDA filed'],
        ['Operations', 'Rachel Kim', 'Dispatch unchanged', 'Fleet replacement plan', 'Purchasing consolidation'],
        ['IT', 'Luis Ortega', 'Email/identity', 'Network & security baseline', 'FSM migration plan (month 6)'],
      ]),
    ];
  }

  if (type === 'Investment Thesis') {
    return [
      disclaimer,
      h(1, `Investment Thesis — ${acq.name}`),
      p(b('Strategy: '), acq.strategy),
      ...(acq.rationale ? [p(b('Why we are interested: '), acq.rationale)] : []),
      h(2, 'Thesis'),
      p(acq.thesis.summary),
      ...acq.thesis.pillars.map((x) => li(x)),
      h(2, 'Screening criteria and what we must prove in diligence'),
      table([['Assumption', 'Playbook expects', 'Current evidence', 'Status'], ...acq.thesis.assumptions.map((a) => [a.label, a.expected, a.current ?? 'Not yet tested', a.status])]),
      h(2, 'Synergy hypotheses'),
      p(i('To be completed by the deal lead. Atlas lists hypotheses from the playbook; values are set by the team.')),
      li('Revenue: cross-sell existing services into the target’s customer base.'),
      li('Cost: purchasing, insurance and back-office consolidation.'),
      li('Capability: talent, licenses or geography the platform lacks.'),
    ];
  }

  if (type === 'Letter of Intent') {
    const lt = acq.loiTerms;
    if (!lt) return [disclaimer, h(1, `Letter of Intent — ${acq.name}`), p('Draft LOI terms on the LOI phase page first; the letter is generated from them.')];
    return [
      disclaimer,
      h(1, `Letter of Intent — ${acq.name}`),
      p(i('Non-binding except for exclusivity, confidentiality and expenses. Draft for review by counsel.')),
      h(2, '1. Transaction'),
      p(`${lt.structure} of ${t.legalName}.`),
      h(2, '2. Purchase price'),
      p(`Enterprise value of $${lt.ev.toFixed(1)}M on a cash-free, debt-free basis with a normalized level of net working capital (${lt.nwcPeg.toLowerCase()}).`),
      table([
        ['Component', 'Amount'],
        ['Cash at closing', `$${lt.cashAtClose.toFixed(1)}M`],
        ['Seller note', lt.sellerNote ? `$${lt.sellerNote.toFixed(1)}M` : '—'],
        ['Earn-out (maximum)', lt.earnoutMax ? `$${lt.earnoutMax.toFixed(1)}M` : '—'],
        ['Equity rollover', lt.rolloverPct ? `${lt.rolloverPct}%` : '—'],
      ]),
      ...(lt.earnoutMax ? [p(b('Earn-out: '), lt.earnoutBasis)] : []),
      h(2, '3. Management'),
      p(lt.managementRetention),
      h(2, '4. Exclusivity and timing'),
      p(`Exclusivity of ${lt.exclusivityDays} days from signing. Confirmatory diligence expected within ${lt.diligenceDays} days.`),
      h(2, '5. Conditions'),
      ...lt.conditions.filter((c) => c.trim()).map((c) => li(c)),
    ];
  }

  if (type === 'IOI Letter') {
    const lo = Math.round(acq.target.ebitda * 5.5 * 10) / 10;
    const hi = Math.round(acq.target.ebitda * 6.5 * 10) / 10;
    return [
      disclaimer,
      h(1, `Indication of Interest — ${acq.name}`),
      p(i('Draft for review by the deal lead and counsel. Non-binding.')),
      h(2, '1. Purchase price'),
      p(`Based on the information provided, we would value 100% of ${t.legalName} at an enterprise value of $${lo.toFixed(1)}M to $${hi.toFixed(1)}M on a cash-free, debt-free basis with a normalized level of working capital. The range applies the playbook guardrail to $${t.ebitda.toFixed(2)}M of ${t.ebitdaBasis.toLowerCase()} EBITDA and is subject to diligence.`),
      h(2, '2. Structure and consideration'),
      p('Purchase of 100% of the equity, primarily cash at close. We may propose a portion of consideration as an earn-out or seller note depending on diligence findings.'),
      h(2, '3. Key diligence areas'),
      ...findings.filter((f) => !f.positive).slice(0, 5).map((f) => li(f.title)),
      ...(findings.length ? [] : [li('Quality of earnings'), li('Customer and contract review'), li('Key people and licensing')]),
      h(2, '4. Timing and approvals'),
      p('We expect to complete confirmatory diligence within 60–75 days of a signed LOI, subject to investment committee approval.'),
      h(2, '5. Conditions'),
      li('Satisfactory due diligence'),
      li('Agreement on key employee and owner transition terms'),
      li('Definitive agreement and customary closing conditions'),
    ];
  }

  if (type === '100-Day Plan') {
    const kpis = s.playbooks.find((pb) => pb.id === acq.playbookId)?.outcomeMetrics ?? [];
    const priorities = s.playbooks.find((pb) => pb.id === acq.playbookId)?.integrationPriorities ?? [];
    return [
      disclaimer,
      h(1, `100-Day Plan — ${acq.name}`),
      h(2, 'Integration priorities (from the playbook)'),
      ...priorities.map((x) => li(x)),
      h(2, 'Plan by period'),
      table([
        ['Period', 'Focus', 'Exit criteria'],
        ['Days 1–30', 'Stabilize: people, customers, cash, compliance', 'No key departures; billing and payroll continuous'],
        ['Days 31–60', 'Align: pay bands, reporting, purchasing', 'Monthly close on platform reporting'],
        ['Days 61–100', 'Capture: synergies, cross-sell, systems roadmap', 'Synergy run-rate on track; systems plan approved'],
      ]),
      h(2, 'Integration KPIs'),
      table([['KPI', 'Target', 'Owner'], ...kpis.map((k) => [k, 'Set by integration lead', name(acq.dealLeadId)])]),
      h(2, 'Integration implications from diligence'),
      ...findings.flatMap((f) => f.implications.filter((x) => x.area === 'Integration').map((x) => li(x.text, ' ', i(`(from: ${f.title})`)))),
    ];
  }

  if (type === 'Target Brief') {
    return [
      disclaimer,
      h(1, `Target Brief — ${acq.name}`),
      p(t.description),
      table([
        ['', ''],
        ['Headquarters', t.hq],
        ['Founded', String(t.founded)],
        ['Revenue', `$${t.revenue.toFixed(1)}M`],
        ['EBITDA', `$${t.ebitda.toFixed(2)}M (${t.ebitdaBasis})`],
        ['Employees', String(t.employees)],
        ['Ownership', t.ownership],
      ]),
      h(2, 'Strategic fit'),
      p(acq.strategy),
      h(2, 'Thesis'),
      ...acq.thesis.pillars.map((x) => li(x)),
      h(2, 'Initial questions'),
      li('How concentrated is revenue by customer?'),
      li('What is the founder’s role in licensing and sales?'),
      li('How durable is the maintenance agreement base?'),
    ];
  }

  // Due Diligence Report
  return [
    disclaimer,
    h(1, `Due Diligence Report — ${acq.name}`),
    table([
      ['Workstream', 'Findings', 'High/Critical'],
      ...Array.from(new Set(findings.map((f) => f.workstream))).map((w) => [wsLabel(w), String(findings.filter((f) => f.workstream === w).length), String(findings.filter((f) => f.workstream === w && (f.severity === 'High' || f.severity === 'Critical')).length)]),
    ]),
    ...keyFindings.map((f) => li(b(f.title + ': '), f.fact.text, ...cite(s, acqId, f.fact.citations))),
  ];
}
